### ISSUE TITLE
[Bug]: Boolean related problems

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

在 chatbot [issue_boolean](https://build.opencui.io/org/me.test/agent/issue_boolean/en/intent/654c9f1da1a5c4c2ac65ba03?tab=annotation) 中，不同 context 下，bot 对于 boolean 相关的 user input 有不同的回复。如下表所示，✅ 表示 bot 表现符合预期，❌ 表示不符合预期

User input \ Type | Prompt of Boolean slot |Explicit confirmation / MV Prompt
-- | -- | --
[Log] | [boolean-slot.txt](https://github.com/framely/community/files/13316808/boolean-slot.txt) | [explicit-confirmation.txt](https://github.com/framely/community/files/13316813/explicit-confirmation.txt) & [mv-prompt.txt](https://github.com/framely/community/files/13316817/mv-prompt.txt)
Yes | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot 
Yes, please | ✅ | Same as above 
Nope | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot  | Same as above 
No / No, thanks | ✅ | ❌ <br>`DU`: IDonotGetIt `DM`: IDonotGetIt 

#### Note
1. The user input is not case-sensitive.
2. The related expressions defined in `io.opencui.core` are:
   - [confirmation.No](https://build.opencui.io/org/io.opencui/agent/core/en/frame/633f953f28e4f04b5f84452c?tab=expression): no
   - [hasMore.No](https://build.opencui.io/org/io.opencui/agent/core/en/frame/633f953f28e4f04b5f84452f?tab=expression): no, nope, that's all, I am good
3. DU **can understand** "that's all", "I am good" when the bot output is MV prompt.

#### Current problem
1. After adding the above user inputs as expressions for explicit confirmation and MV prompt, the results remain the same. It seems that builder-provided **Affirmatives and Negatives do NOT work**.

2. When there are **both a multi-valued slot and a boolean slot** in one frame, the result will be different when the user input is "No, thanks". For example
   - if there is only one multi-valued slot in a frame, the result will be like this:
      > Bot: Any more toppings?
      > User: No, thanks
      > Bot: Sorry, I did not get that. Any more toppings?
   - However, if there are both a multi-valued slot and a boolean slot, the result will be like:
     > Bot: Any more toppings?
     > User: No, thanks
     > Bot: Alright. How many Cheese Pizza would you like?

   This difference occurs because DU recognizes the user input as the value of the boolean slot. Due to the prompt strategy of the multi-valued slot, which is a conditional prompt when the boolean slot is true, when the value of the boolean slot is false, the multi-valued slot doesn't need to be filled. DM moves on to fill the next slot instead of continuing to fill the multi-valued slot.

### Expected Behavior

User input \ Type | Prompt of Boolean slot | Explicit confirmation | MV Prompt
-- | -- | -- | --
Yes / Yes,please | `DU`: BooleanSlot <br>`DM`: Fill slot with value **true** | `DU`: confirmation.Yes <br>`DM`: Move on to the next dialog act | `DU`: hasMore.Yes <br>`DM`: Output the prompt of current slot
Nope / No / No, thanks | `DU`: BooleanSlot <br>`DM`: Fill slot with value **false** | `DU`: confirmation.No <br>`DM`: Refill the current slot | `DU`: hasMore.No <br>`DM`: Move on to the next dialog act

1. The chatbot should follow the behavior described in the table above.

2. After adding the user inputs provided in the table as expressions for explicit confirmation and MV prompt, the chatbot should be able to understand the expressions added in the Affirmatives and Negatives fields provided by the builder.

### Use Case

目前在 [foodOrderingApp](https://build.opencui.io/org/me.test/agent/foodOrderingApp/en/type?page=0&imported=false&search=&category=ALL) 中，有以下对话涉及 boolean 相关的 user input，目前预期和实际表现不符

1. **Prompt of Boolean slot** 

   目前 user 回复 "yes, please", bot 能有预期表现

   > B: Perfect! Would you like any additional toppings on your Cheese Pizza? 
   > U: Yes 
   > B(Current): Perfect! Would you like any additional toppings on your Pepperoni Pizza? 
   > B(Expected): **Which toppings would you like?...** 
   
   
2. **MV prompt of entity slot**

   > B: Great choice! Any more toppings?
   > U: No
   > B(Current):`DU`: kotlin.Boolean [回复符合预期但 DU 的输出不符合]
   > B(Expected): `DU`: **hasMore.No**

3. **MV prompt of frame slot**

   目前 user 回复 "that's all", bot 能有预期表现

   > B: Is there anything else you would like to order?
   > U: No
   > B(Current): Sure! What type of food are you in the mood for? 
   > B(Expected): **Alright, your order consists of...**
   

4. **Explicit confirmation**

   目前传入 frame event `[{"type":"Yes", "packageName": "io.opencui.core.confirmation"}]`, bot 能有预期表现

   > B: ...The total comes to $23.0. Does that sound good to you?
   > U: Yes
   > B(Current): ..The total comes to $23.0. Does that sound good to you?
   > B(Expected): **Great! Thank you for choosing to order with us...**

### Steps To Reproduce

1. 进入 chatbot [issue_boolean](https://build.opencui.io/org/me.test/agent/issue_boolean/en/intent/654c9f1da1a5c4c2ac65ba03?tab=annotation)
2. 点击 Debug，再点击 Test Cases 可以查看之前保存的测试记录
3. 进入对应的测试，点击 RUN 即可复现上述表现

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.test/agent/issue_boolean/en/type?page=0&imported=false&search=&category=ALL

**Comment by hisunnymay** [comment]
## Update 12/20/2023

Add a new test for **Gated prompt**. The result is the same as boolean slot, explicit confirmation and MV Prompt.

### Current Behavior
User input \ Type | Prompt of Boolean slot |Explicit confirmation & MV Prompt <br>& Gated Prompt
-- | -- | --
[Log] | [boolean-slot.txt](https://github.com/framely/community/files/13316808/boolean-slot.txt) | [explicit-confirmation.txt](https://github.com/framely/community/files/13316813/explicit-confirmation.txt) & [mv-prompt.txt](https://github.com/framely/community/files/13316817/mv-prompt.txt)  <br>& [Gated.txt](https://github.com/framely/community/files/13722392/Gated.txt)
Yes | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot 
Yes, please | ✅ | Same as above 
Nope | ❌ <br>`DU`: IntentClarification <br>`DM`: Output the prompt of the current slot  | Same as above 
No / No, thanks | ✅ | ❌ <br>`DU`: IDonotGetIt `DM`: IDonotGetIt 

### Expected Behavior

User input \ Type | Prompt of Boolean slot | Explicit confirmation | MV Prompt | Gated Prompt
-- | -- | -- | -- | --
Yes / Yes,please | `DU`: BooleanSlot <br>`DM`: Fill slot with value **true** | `DU`: confirmation.Yes <br>`DM`: Move on to the next dialog act | `DU`: hasMore.Yes <br>`DM`: Output the prompt of current slot | `DU`: booleanGate.Yes <br>`DM`: Move on to the next dialog act
Nope / No / No, thanks | `DU`: BooleanSlot <br>`DM`: Fill slot with value **false** | `DU`: confirmation.No <br>`DM`: Refill the current slot | `DU`: hasMore.No <br>`DM`: Move on to the next dialog act | `DU`: booleanGate.No <br>`DM`: Move on to the next dialog act

**Comment by hisunnymay** [comment]
Prompt of Boolean slot，Explicit confirmation 和 MV Prompt 都能 work 了，还剩 **Gated prompt** 有问题：
目前 bot 输出 Gated prompt 后，user 回复 “yes” 会有报错：
```
error : java.lang.ClassCastException: class io.opencui.core.BoolGate cannot be cast to class io.opencui.core.IIntent (io.opencui.core.BoolGate and io.opencui.core.IIntent are in unnamed module of loader org.springframework.boot.loader.thin.ThinJarLauncher$ThinJarClassLoader @59cda16e)
	at io.opencui.core.ResumeIntent$createBuilder$1$invoke$1$1.set(io_opencui_core.kt:359)
	at io.opencui.core.AnnotatedWrapperFiller.directlyFill(filler.kt:606)
```

- 详见：[error-log_0208.txt](https://github.com/framely/community/files/14209620/error-log_0208.txt)
- Chatbot: [me.test.issueBoolean](https://build.opencui.io/org/me.test/agent/issueBoolean/en/type)

**Comment by hisunnymay** [comment]
Checked, all fixed. Test cases are saved in [me.test.issueBoolean](https://build.opencui.io/org/me.test/agent/issueBoolean/en/type).
