### ISSUE TITLE
[Bug]: Inconsistent testing result every time deploying provider

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

目前在不修改Provider：[reservationProvider_0426](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62674d244d871ce8b200d508/service_schema) 的前提下，仅进行 `commit` + `deploy` 的操作，然后测试function: checkDate，每次测试值相同，会随机出现以下4种测试结果：
> 测试值：userId_param：666286199349972992, date_param ：2022-4-27

1.  预期的结果，返回[]

![image](https://user-images.githubusercontent.com/95261974/165423470-412ad7ab-d474-4141-8867-3b70a0d86c20.png)

2. 报错："Returned type bigint does not match expected type time without time zone in column 1."

![image](https://user-images.githubusercontent.com/95261974/165423679-9b9be2ab-de75-4b6c-a49e-b6ea45435860.png)

3. 报错："Returned type bigint does not match expected type text in column 1."

![image](https://user-images.githubusercontent.com/95261974/165423860-a7f2642f-069f-4509-8c9e-202842c6ef53.png)

4. 报错："Returned type bigint does not match expected type date in column 1."

![image](https://user-images.githubusercontent.com/95261974/165424019-05414f39-220f-4c03-b9ba-6524c19c75cd.png)

### Expected Behavior

在不修改Provider：[reservationProvider_0426](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62674d244d871ce8b200d508/service_schema) 的前提下，仅进行 `commit` + `deploy` 的操作，然后测试function: checkDate，每次测试值相同，测试结果应该都是：预期结果，返回[]

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62674d244d871ce8b200d508/service_schema

### Additional information

Function: checkDate的定义如下图所示，作用是：如果end-user之前预定过相同日期的餐桌，那么会返回之前的预定信息

![image](https://user-images.githubusercontent.com/95261974/165424953-38ed6ea7-94a9-483f-bb6f-e0af3141bbd7.png)

**Comment by hisunnymay** [comment]
补充：

1. 当Function testing: checkDate报错，再在Chatbot：[reservationApp_0425](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62667045132e5d9cbc15b3c8/intent) 中测试，`commit` + `try it now` ,  调用了checkDate的confirmation没有输出prompt。

![image](https://user-images.githubusercontent.com/95261974/165426122-2b2f32e3-56ce-46ca-a798-ab078d3aaf0c.png)


2. 当Function testing: checkDate正常work，再在Chatbot：[reservationApp_0425](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62667045132e5d9cbc15b3c8/intent) 中测试，`commit` + `try it now` ,  调用了checkDate的confirmation输出了prompt。

![image](https://user-images.githubusercontent.com/95261974/165426139-3ffde646-ed20-440b-88b9-27f23ef2756f.png)

3. 除了function: checkDate，function：getTableTypeFrame和getTimeFrame也出现过类似的测试结果不稳定的情况

**Comment by hisunnymay** [comment]
4. 当function: getInfo，出现类似的报错时（"Returned type bigint does not match expected type date in column 1."），chatbot的报错提示是：

> Failed to get reply: io.framely.core.ClosureInvokeException: We are expecting an ArrayNode here.
        at io.framely.provider.PostgrestListClosure.invoke(service.kt:888) at o18810675122.reservationApp_0425.reservationProvider_0426.getInfo(o18810675122_reservationApp_0425.kt:630)

**Comment by hisunnymay** [comment]
上述问题好像是因为每次 `commit` + `deploy` 生成的 Return type 不一样导致的。当 id 不是 return table 中第一个参数时，会有上述的报错
1. 正确的 Return type

![image](https://user-images.githubusercontent.com/95261974/179454509-bd41ec65-11d7-4c22-89cd-f6f59cb9fd30.png)

2. 会导致报错的 Return type

![image](https://user-images.githubusercontent.com/95261974/179453734-61b1d164-f2fd-4779-b58d-3723b747871b.png)

![image](https://user-images.githubusercontent.com/95261974/179455645-fd819c8c-928b-43a2-87bb-7fef635c8cfe.png)
