### ISSUE TITLE
[Bug]: Condition failed in state update

### ISSUE THREAD

**Issue by yigexu** [framely/community#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

# 问题简述
我认为 state update 的 condition，在 function invocation 模式下，选择 mv slot `is not empty` 没有正确地被实现

# bot 配置
playground.testSlotUpdate_copy2.MV
- 有 MV slot：from_list, to_list，type 都是 City[]
- 有 State Update

模式1
<img width="1244" alt="Screen Shot 2022-05-11 at 3 07 31 PM" src="https://user-images.githubusercontent.com/6505755/167790596-ab3e97d8-9fb4-4b6c-a5bb-084a455cf00e.png">
模式2
<img width="1244" alt="Screen Shot 2022-05-11 at 3 09 51 PM" src="https://user-images.githubusercontent.com/6505755/167790606-238eb3b6-c8d7-4e0e-8c52-f745d4a537cd.png">

# 具体问题
理论上，我认为两种模式的体验应该相同
实际上，输入 book mv, beijing
模式1 会继续对话
模式2 会报错 (位置应该是 第二条 state update，也就是 `to_list Not empty`; 这条是我猜的)
```java
Failed to get reply: java.lang.NullPointerException
	at playground.testSlotUpdate_copy2.MV.searchStateUpdateByCondition(playground_testSlotUpdate_copy2.kt:530)
	at io.framely.core.SlotPostAskAction.run(action.kt:590)
	at io.framely.core.DialogManager.response(execution.kt:103)
	at io.framely.core.DialogManager.response(execution.kt:52)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:109)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
...
```

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

playground /testSlotUpdate_copy2

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/627b6095b0abf826f66dbd3a/intent/6278ae586a4467792de7fb1b?tab=3

**Comment by XiaoboYuan** [comment]
fixed
