### ISSUE TITLE
[Bug]: After add some expression in en, bot performs unexpectedly

### ISSUE THREAD

**Issue by yigexu** [framely/community#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

1. 创建一个bot，配置 reply “bye”，intent expression “test”
2. commit，测试 test，能看到表现正常；
3. pr
4. 在 en 上补充 intent expression “buy”
5. commit，测试 buy，能看到表现不正常：try it now 没有 reply，也就是 bye；日志报错。
（我让 Chang 也帮忙测试了一下，效果和#5相同）

相关信息：
1. 操作视频
https://user-images.githubusercontent.com/6505755/170164654-0edc3e46-65e6-4d6e-b27e-44cb34ceadd9.mov

2. 日志报错
```
01:53:30.670 [http-nio-8080-exec-5] INFO  io.framely.core.DialogManager - session state before turn 2 : {"schedulers_count":1,"main":{"state":"POST_ASK","fillers":[{"filler_type":"AnnotatedWrapperFiller","attribute":"Main"},{"filler_type":"FrameFiller","attribute":"Main"},{"filler_type":"AnnotatedWrapperFiller","attribute":"skills"},{"filler_type":"MultiValueFiller","attribute":"skills"},{"filler_type":"AnnotatedWrapperFiller","attribute":"skills._hast"},{"filler_type":"FrameFiller","attribute":"skills._hast"},{"filler_type":"AnnotatedWrapperFiller","attribute":"status"},{"filler_type":"InterfaceFiller","attribute":"status"},{"filler_type":"AnnotatedWrapperFiller","attribute":"status._realtype"},{"filler_type":"RealtypeFiller","attribute":"status._realtype"}]}}
java.lang.ClassNotFoundException: io.framely.core.IDonotGetIt
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:460)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at io.framely.core.UserSession.construct(UserSession.kt:538)
	at io.framely.core.BaseKt$createFrameGenerator$1.invoke(base.kt:49)
	at io.framely.core.BaseKt$createFrameGenerator$1.invoke(base.kt:44)
	at io.framely.core.InterfaceFiller$askFiller$2$entityFiller$2.invoke(filler.kt:875)
	at io.framely.core.InterfaceFiller$askFiller$2$entityFiller$2.invoke(filler.kt:875)
	at io.framely.core.RealtypeFiller.isCompatible(filler.kt:379)
	at io.framely.core.UserSession.kernelStep(UserSession.kt:250)
	at io.framely.core.UserSession.userStep(UserSession.kt:203)
	at io.framely.core.DialogManager.response(execution.kt:95)
	at io.framely.core.DialogManager.response(execution.kt:53)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:109)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Applicati
```

3. 同样的操作，我曾经还有过第五步在 try it now 直接报错

```
08:37:31.953 [http-nio-8080-exec-9] INFO  i.framely.dispatcher.FrameController - body: FramelyRequest(text=buy, sessionId=582228474861719552, initial=false, events=[])
08:37:31.953 [http-nio-8080-exec-9] INFO  i.framely.dispatcher.FrameController - query : buy; session id : 582228474861719552; org name: playground; agent id : testCommit; lang : en; branch : 582228474861719552; chosenBranch : 582228474861719552; body : FramelyRequest(text=buy, sessionId=582228474861719552, initial=false, events=[])
08:37:31.953 [http-nio-8080-exec-9] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: playground/testCommit/Main$createBuilder$1$invoke$2$1] with root cause
java.lang.NoClassDefFoundError: playground/testCommit/Main$createBuilder$1$invoke$2$1
	at playground.testCommit.Main$createBuilder$1$invoke$2.invoke(playground_testCommit.kt:149)
	at playground.testCommit.Main$createBuilder$1$invoke$2.invoke(playground_testCommit.kt:148)
	at io.framely.core.MultiValueFiller.createTFiller(filler.kt:1022)
	at io.framely.core.MultiValueFiller.access$createTFiller(filler.kt:929)
	at io.framely.core.MultiValueFiller$singleTargetFiller$2.invoke(filler.kt:944)
	at io.framely.core.MultiValueFiller$singleTargetFiller$2.invoke(filler.kt:944)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at io.framely.core.MultiValueFiller.getSingleTargetFiller(filler.kt:944)
	at io.framely.core.MultiValueFiller.getSvType(filler.kt:969)
	at io.framely.core.DialogManager.findExpectationByFiller(execution.kt:251)
	at io.framely.core.DialogManager.findDialogExpectation(execution.kt:200)
	at io.framely.core.DialogManager.response(execution.kt:43)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:109)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor89.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

### Expected Behavior

/

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

我推荐按照视频自己操作一遍，因为我也不确定是不是和账号、分支有关

### Framely Link

https://framely.naturali.io/org/6098bfbbac80fbf349c38d2b/agent/628d8f184784d3c3c1d289dd/intent/628d8f214784d3c3c1d289df?tab=4

**Comment by yigexu** [comment]
@XiaoboYuan 这是昨天那个问题的延续。
1. 我按照昨天的配置步骤，重新操作了一遍，虽然表现不一样了，但是仍旧不是正确表现。
2. 昨天、今天的两种不同的错误表现， @hisunnymay 也有。

另外，@jfang137，我不确定是不是需要你帮忙看，所以也 assign 了一下

**Comment by jfang137** [comment]
好的，我也在看

**Comment by hisunnymay** [comment]
@XiaoboYuan @jfang137 我这里也有类似的问题：将en的内容pr之后，try it now的response的内容还是上一个版本的。

- 期望的结果是：左右两个蓝色框中的内容应该是一样的。
- chatbot：[restaurantDemo_0524](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/628cab7f4784d3c3c1d20eb8/intent)

![image](https://user-images.githubusercontent.com/95261974/170169818-fa00613b-de38-4e14-b1b6-e77b4d73fce1.png)

**Comment by jfang137** [comment]
@XiaoboYuan 我发现的问题是，用户分支只有第一次提测try-it-now是正常的，之后的提测，try-it-now都是维持第一次提测的表现

**Comment by xiaoyunwu** [comment]
@XiaoboYuan is this the side effect of the

**Comment by XiaoboYuan** [comment]
> @XiaoboYuan 我发现的问题是，用户分支只有第一次提测try-it-now是正常的，之后的提测，try-it-now都是维持第一次提测的表现

维持第一次的表现是指？

**Comment by jfang137** [comment]
第二次及以后传给code gen的数据都没有生效

**Comment by XiaoboYuan** [comment]
> 第二次及以后传给code gen的数据都没有生效

生效是通过tryitnow的表现判断的吗？

**Comment by jfang137** [comment]
是的

**Comment by XiaoboYuan** [comment]
> 是的

你说的是meichang的case？yige的case表现是不一样的

**Comment by XiaoboYuan** [comment]
我的test表现也不一样

**Comment by jfang137** [comment]
我自己新建的agent按她们的步骤试的

**Comment by yigexu** [comment]
我和 chang 的表现在具体细节上可能不一样，但是感觉都是因为一个原因导致的，所以可以先挑一个试一试。
@XiaoboYuan 你现在能复现吗？

**Comment by yigexu** [comment]
@xiaoyunwu 这个为甚么 close 了，我们现在用 bot 表现的还是不对

**Comment by XiaoboYuan** [comment]
@yigexu 的那个log我还是没办法复现 但是修复了一个相关的问题 可以再试一下
可以确定的是现在修改expression还是不能马上生效，但是修改别的部分response或者prompt之类的已经可以生效了
expression还得再修复一下

**Comment by xiaoyunwu** [comment]
I think we should have two entry points for definition change: one is
existing one, and one is for auto completion, which will be as light as
possible.

**Comment by XiaoboYuan** [comment]
@yigexu @hisunnymay @jfang137 
修复了一些东西 可以试试你们的问题
问题我不是都能复现，所以没有一个一个去看

**Comment by yigexu** [comment]
我这边暂时没问题，先 close 了
