### ISSUE TITLE
[Bug]: NullPointerException when Value Check fails

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

如果使用 Recovering Strategy clear current slot之前的slot，当Value Check fails时，会出现 NullPointerException 的报错

- 报错如下：
```
Failed to get reply: java.lang.NullPointerException
	at Demo.ValueCheck.Test.checkBothNum(Demo_ValueCheck.kt:522)
	at Demo.ValueCheck.Test$annotations$3.invoke(Demo_ValueCheck.kt:515)
	at Demo.ValueCheck.Test$annotations$3.invoke(Demo_ValueCheck.kt:514)
	at io.framely.core.AnnotatedWrapperFiller.getCheckDone(filler.kt:1242)
	at io.framely.core.AnnotatedWrapperFiller.filled(filler.kt:714)
	at io.framely.core.AnnotatedWrapperFiller.done(filler.kt:718)
	at io.framely.core.UserSession.searchForRefocusChild(UserSession.kt:628)
	at io.framely.core.UserSession.tryToRefocus(UserSession.kt:584)
	at io.framely.core.UserSession.kernelStep(UserSession.kt:278)
	at io.framely.core.UserSession.userStep(UserSession.kt:202)
	at io.framely.core.DialogManager.response(execution.kt:95)
	at io.framely.core.DialogManager.response(execution.kt:53)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:109)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
- [Intent：Test](https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/6297f6d04cfdb2515448d812/intent/62a1935365642d7091fdcbf6) 的Value Check的配置为

![image](https://user-images.githubusercontent.com/95261974/172805108-e5b00b34-f8d3-4ee1-a33c-5a49bb032a1b.png)

- 补充
如果把 num_2 的 Condition 换成 `checkBothNum(11, num_2) == true`，Value Check fail后就不会报错。
看上去像是 num_2 的 Value Check fails之后，clear 了 num_1 ， 然后又调用了 num_2 的 Value Check。因为 num_1 被clear了，所以导致了 NullPointerException 的报错。但是 num_1 的  Value Check fail 之后，clear num_1 后，没有报错。

### Expected Behavior

在上述配置中，使用 Recovering Strategy clear current slot之前的slot，当Value Check fails时，不会出现 NullPointerException 的报错

### Steps To Reproduce

在 [ValueCheck](https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/6297f6d14cfdb2515448d814/intent/62a1935365642d7091fdcbf6/slot/62a19a0165642d7091fdcdf1) 中用try it now，依次输入以下内容
1. test
2. 1
3. 222

### Framely Link

https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/6297f6d14cfdb2515448d814/test_case

**Comment by XiaoboYuan** [comment]
fixed

**Comment by hisunnymay** [comment]
Checked, result stoed in [Test 0617](https://framely.naturali.io/org/622c8ff683536204fe062b55/agent/6297f6d14cfdb2515448d814/test_case)
