### ISSUE TITLE
[Bug]: NPE from current master

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

- 在 `try-it-now`中，输入 *xxx* > *today* 没有报错
- 在 Facebook Messenger Channel 输入 *xxx* 没有报错， 再输入 *today* 时报错：
```
Caused by: java.lang.NullPointerException
	at o18810675122.reservation_0602.MakeReservation.searchConfirmation(o18810675122_reservation_0602.kt:276)
	at o18810675122.reservation_0602.MakeReservation$annotations$2.invoke(o18810675122_reservation_0602.kt:223)
	at o18810675122.reservation_0602.MakeReservation$annotations$2.invoke(o18810675122_reservation_0602.kt:219)
	at io.framely.core.AnnotatedWrapperFiller.getConfirmDone(filler.kt:582)
	at io.framely.core.AnnotatedWrapperFiller.filled(filler.kt:739)
	at io.framely.core.AnnotatedWrapperFiller.done(filler.kt:743)
	at io.framely.core.UserSession.searchForRefocusChild(UserSession.kt:693)
	at io.framely.core.UserSession.tryToRefocus(UserSession.kt:649)
	at io.framely.core.UserSession.kernelStep(UserSession.kt:282)
	at io.framely.core.UserSession.userStep(UserSession.kt:206)
	at io.framely.core.DialogManager.response(execution.kt:95)
```

### Steps To Reproduce

1. xxx
2. today
![image](https://user-images.githubusercontent.com/95261974/176347631-eff33b8e-5701-4853-97c2-e80607690013.png)

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/62ba6bd71d9feb201b171ff1/version

**Comment by hisunnymay** [comment]
重新试了一下，现在没有这个报错了
