### ISSUE TITLE
[issue]: NPE when saying "I want to order some food"

### ISSUE THREAD

**Issue by yigexu** [framely/community#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

1. Background 是今天 clone [restaurantC214](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/6209b806ff5c77cdfc256ce4/intent) 到 [restaurantC214_region](https://framely.naturali.io/org/6209b54dff5c77cdfc255577/agent/62c51c40dcc575bafb6eb88f/intent)
2. After clone，connect 输入 “I want to order some food” 会出现 NPE
```
MainDishMainDishMainDishMainDishMainDishMainDish05:43:13.704 [http-nio-8080-exec-2] ERROR i.framely.dispatcher.FrameController - fail to response for query : I want to order some food; error : java.lang.NullPointerException
	at restaurant002.restaurantL214.DynamicSuggestion$_rec_target$1.invoke(restaurant002_restaurantL214.kt:584)
	at restaurant002.restaurantL214.DynamicSuggestion$_rec_target$1.invoke(restaurant002_restaurantL214.kt:583)
	at io.framely.core.PagedSelectable.getCandidates(compiled.kt:960)
	at io.framely.core.PagedSelectable$annotations$3.invoke(compiled.kt:1143)
	at io.framely.core.PagedSelectable$annotations$3.invoke(compiled.kt:1141)
	at io.framely.core.LazyEvalCondition.invoke(annotation.kt:87)
	at io.framely.core.LazyEvalCondition.invoke(annotation.kt:84)
	at io.framely.core.ConditionalAsk.canEnter(annotation.kt:177)
	at io.framely.core.AnnotatedWrapperFiller.canEnter(filler.kt:731)
	at io.framely.core.AnnotatedWrapperFiller.done(filler.kt:743)
	at io.framely.core.FrameFiller.findNextChildFiller(filler.kt:842)
	at io.framely.core.FrameFiller.findNextFiller(filler.kt:837)
	at io.framely.core.FrameFiller.done(filler.kt:849)
	at io.framely.core.AnnotatedWrapperFiller.filled(filler.kt:739)
	at io.framely.core.AnnotatedWrapperFiller.move(filler.kt:718)
	at io.framely.core.Scheduler.grow(UserSession.kt:55)
	at io.framely.core.RescheduleAction.run(action.kt:506)
	at io.framely.core.DialogManager.response(execution.kt:104)
	at io.framely.core.DialogManager.response(execution.kt:53)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:109)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
...
```
3. 一些关联的信息
- 不知道是不是跟 vr starting point，我还没有针对 vr starting point 做过适配性的改动
- 被 clone 的 bot 昨天可以正常对话，因为 region 配置的问题今天被 clone 的 instance 用不了；不排除是 clone 导致的问题
- 我在 DynamicSuggestion 的 slot target 的 prompt - condition 中打了一些日志，因为 prompt 在 vr 之前；但是 log 里没有我的日志

### Expected Behavior

问想要什么 main dish，noodle or rice

### Use Case

/

### Steps To Reproduce

/

### Label of org.project

见上

### Framely Link

见上

**Comment by yigexu** [comment]
今天同样的操作，会出现
<img width="960" alt="Screen Shot 2022-07-21 at 2 38 50 PM" src="https://user-images.githubusercontent.com/6505755/180146769-16111648-3bc7-486c-871c-a04ad92604ab.png">

**Comment by yigexu** [comment]
fixed
