### ISSUE TITLE
[Bug]: Get errors when deserializing return value from postgrest function

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using Framely on Google Chrome!

- [X] I used Framely on Google Chrome

### Current Behavior

在Chatbot：[reservationApp_0607](https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/629eae79faa19d508441a99e/intent) 中，调用 Function：checkDate ，返回值是 `o18810675122.reservation_0602.ReservationInfo` ，会报错：
_Cannot deserialize instance of `o18810675122.reservation_0602.ReservationInfo` out of START_ARRAY token_

<details><summary>Error messages</summary>

```
Failed to get reply: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `o18810675122.reservation_0602.ReservationInfo` out of START_ARRAY token
 at [Source: UNKNOWN; line: -1, column: -1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1464)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1238)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:604)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:190)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4453)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2696)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3149)
	at io.framely.serialization.Json$getFrameConverter$1.invoke(serialization.kt:143)
	at io.framely.provider.PostgrestConnection.invoke(service.kt:94)
	at o18810675122.reservationApp_0607.reservationProvider_0602.checkDate(o18810675122_reservationApp_0607.kt:784)
	at o18810675122.reservation_0602.MakeReservation.searchConfirmation(o18810675122_reservation_0602.kt:274)
	at o18810675122.reservation_0602.MakeReservation$annotations$2.invoke(o18810675122_reservation_0602.kt:221)
	at o18810675122.reservation_0602.MakeReservation$annotations$2.invoke(o18810675122_reservation_0602.kt:217)
	at io.framely.core.AnnotatedWrapperFiller.getConfirmDone(filler.kt:593)
	at io.framely.core.AnnotatedWrapperFiller.filled(filler.kt:740)
	at io.framely.core.AnnotatedWrapperFiller.done(filler.kt:744)
	at io.framely.core.UserSession.searchForRefocusChild(UserSession.kt:705)
	at io.framely.core.UserSession.tryToRefocus(UserSession.kt:661)
	at io.framely.core.UserSession.kernelStep(UserSession.kt:275)
	at io.framely.core.UserSession.userStep(UserSession.kt:202)
	at io.framely.core.DialogManager.response(execution.kt:95)
	at io.framely.core.DialogManager.response(execution.kt:53)
	at io.framely.sessionmanager.SessionManager.getReply(SessionManager.kt:110)
	at io.framely.dispatcher.FrameController.postResponse(DispatchService.kt:118)
	at jdk.internal.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
</details>

<details><summary>ReservationInfo 的定义</summary>

![image](https://user-images.githubusercontent.com/95261974/182286138-d7a445e7-9544-400b-90d3-8e48d3418ed6.png)

</details>

注：7月1日测试时没有报错，之后和 Postgrest Provider 有关的修改有：
1. 将 id 的类型 从 integer 改为 bigint [[Feature Request]: make database int consistent](https://github.com/framely/community/issues/289#top)
2. https://github.com/framely/runtime/pull/893/files

### Steps To Reproduce

在 try-it-now 中输入
1. make a reservation
2. Wednesday

### Framely Link

https://framely.naturali.io/org/615fa4282cc41400665536e3/agent/629eae79faa19d508441a99e/setting

**Comment by hisunnymay** [comment]
Checked, fixed.
