### ISSUE TITLE
[Bug]: No response in any channel

### ISSUE THREAD

**Issue by hisunnymay** [framely/community#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Make sure you are using OpenCUI on Google Chrome!

- [X] I used OpenCUI on Google Chrome

### Current Behavior

先在 Debug 测试 MakeReservation skill，通过之后，将 chatbot deploy 到 Messenger & WhatsApp，点击 Clear Cache

在成功配置了 webhook 后，在 Messenger 给 bot 发送 “_hi_” 之后，能收到回复

再发送 "_I want to book a table_" 后，bot 没有回复，对话如下图所示

![image](https://user-images.githubusercontent.com/95261974/221487843-900a821c-005c-468e-ac18-5df9519049a9.png)

log 中有下列报错：

```
ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] 
in context with path [] threw exception [Request processing failed; 
nested exception is java.util.NoSuchElementException: List is empty.] with root cause 
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
        at me.restaurant.tableReservation.MakeReservation$SlotInitduration_Action$1.invoke(me_restaurant_tableReservation.kt:344)
```

在 WhatsApp 重复上述操作，有相同的报错

### Log

1. [messenger-error_0227.txt](https://github.com/framely/community/files/10836581/messenger-error_0227.txt)
2. [whatsapp-error_0227.txt](https://github.com/framely/community/files/10836582/whatsapp-error_0227.txt)
3. [debug-log_0227.txt](https://github.com/framely/community/files/10837027/debug-log_0227.txt)

### Expected Behavior

期望 bot 回复："_How many people will you need the reservation for?_"

### Use Case

/

### Steps To Reproduce

在 WhatsApp 或者 Messenger 中给 bot 发消息

### Label of org.project

/

### OpenCUI Link

https://build.opencui.io/org/me.restaurant/agent/tableReservationApp/en/test_case

### Additional information

最近一次 Messenger 能 work 的日期是：2月16日 14:46，WhatsApp ：2月15日 11:14

**Comment by hisunnymay** [comment]
Update 23/03/01

目前把 Location 中的 name slot 改为了 always ask，该问题暂时得到解决，先 close 了
